### ISSUE TITLE
Quotes schema error

### ISSUE THREAD

**Issue by quezak** [coinpaprika/coinpaprika.github.io#1]
Your `Quotes` schema defines a single required property named `$KEY`. This way, API clients generated with [openapi-generator](https://github.com/OpenAPITools/openapi-generator/) have incorrect response typings. In my case, for target `typescript-node`, this leads to the `Tick.quotes` field to always be empty -- because the server's response doesn't contain a `$KEY` property, and undefined properties are not deserialized into the typed response.

I think that `quotes` should be a [dictionary](https://swagger.io/docs/specification/data-models/dictionaries/) of `Quote` objects instead. I've tested that this way the response is properly typed and deserialized. I've prepared a fix and I'll submit a PR shortly.

**Comment by apralat** [comment]
You are right, thanks for PR :) 👍
