### ISSUE TITLE
add coin_logo in Get coin by ID

### ISSUE THREAD

**Issue by oliverlj** [coinpaprika/coinpaprika.github.io#4]
Hi and thanks for this great api

Is it possible to add an coin_logo_url on api get coin by ID ?

**Comment by oskarwojciski** [comment]
Coin logo can be accessed by url:
`https://coinpaprika.com/coin/{coin_id}/logo.png`, but we provide only data with API, no assets, so you have to use your own storage to serving the logos for your need
